image: nfcore/gitpod:latest

vscode:
  extensions: # based on nf-core.nf-core-extensionpack
    - codezombiech.gitignore                 # Language support for .gitignore files
    - davidanson.vscode-markdownlint         # Markdown/CommonMark linting and style checking for Visual Studio Code
    - EditorConfig.EditorConfig              # override user/workspace settings with settings found in .editorconfig files
    - mechatroner.rainbow-csv                # Highlight columns in csv files in different colors
    - nextflow.nextflow                      # Nextflow syntax highlighting
    - oderwat.indent-rainbow                 # Highlight indentation level
    - streetsidesoftware.code-spell-checker  # Spelling checker for source code
